### PR TITLE
actually add gcloud

### PR DESCRIPTION
**Pull request by raybellwaves**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Forgot to add gcloud in https://github.com/conda-forge/xee-feedstock/pull/2

### CODE REVIEW

**Comment by raybellwaves** [comment]
@conda-forge-admin, please rerender

**Comment by giswqs** [comment]
Please do not add gcloud as a dependency. It is unnecessary.

**Comment by giswqs** [comment]
See https://github.com/conda-forge/xee-feedstock/pull/2#discussion_r1358504060

**Comment by raybellwaves** [comment]
ah it previosuly got removed, sorry I missed that. No problem @giswqs . I can't see your comment on why it's not needed. See image below if what I see when I click on the hyperlink

Screenshot 2023-10-17 at 2 00 34 PM

It is the dependency is too large and is only needed for authentication which can be done in a seperate environment?

Edit: I apologize if the title and commit message comes across as snarky. I thought I forgot to add it when I made the earlier to PR.

**Comment by raybellwaves** [comment]
@giswqs, you're welcome to close this. I realized I made a made a mistake of the package name for gcloud on conda so I fixed that for posteritiy but welcome to leave this out

**Comment by giswqs** [comment]
Here is what I commented in the previous PR. gcloud makes the package unnecessary large. It is not needed. 

image

**Comment by giswqs** [comment]
I have removed gcloud.

**Comment by raybellwaves** [comment]
I'm happy for `gcloud` to be left out but from what I can tell `ee.Authenticate()` uses gcloud under the hood

```
>>> ee.Authenticate()
Fetching credentials using gcloud
Traceback (most recent call last):
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/ee/oauth.py", line 317, in _load_app_default_credentials
    subprocess.run(command, check=True)
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gcloud'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/ee/__init__.py", line 104, in Authenticate
    oauth.authenticate(
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/ee/oauth.py", line 422, in authenticate
    _load_app_default_credentials(auth_mode == 'gcloud', scopes, quiet)
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/ee/oauth.py", line 320, in _load_app_default_credentials
    raise Exception('gcloud command not found. ' + tip) from e  # pylint:disable=broad-exception-raised
Exception: gcloud command not found. Please ensure that gcloud is installed.
More information: https://developers.google.com/earth-engine/guides/python_install
```

**Comment by giswqs** [comment]
I am not sure if GEE has change its default authentication method, but you can use this without gcloud. 

```python
ee.Authenticate(auth_mode='notebook')
```

**Pull request merged**
